version: '3.1'
secrets:
  db_password:
    file: ./secrets/db_password
  django_secret:
    file: ./secrets/django_secret
  email_password:
    file: ./secrets/email_password
  email_user:
    file: ./secrets/email_user
  email_host:
    file: ./secrets/email_host
  db_url:
    file: ./secrets/db_url
  stripe_pk:
    file: ./secrets/stripe_pk
  stripe_sk:
    file: ./secrets/stripe_sk
  gigo_password:
    file: ./secrets/gigo_password
  gigo_email:
    file: ./secrets/gigo_email
  mailgun_key:
    file: ./secrets/mailgun_key
services:
  db:
    environment:
      POSTGRES_DB: streetnoise_cms
      POSTGRES_USER: streetnoise_cms
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    user: "3993:3993"
    restart: always
    image: postgres:14
    expose:
      - "5432"
    ports:
      - "127.0.0.1:5440:5432/tcp"
    volumes:
      - /srv/streetnoise.at/postgres14:/var/lib/postgresql/data/:rw
    secrets:
      - db_password
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
  cms:
    restart: always
    environment:
      DJANGO_SECRET_KEY_FILE: /run/secrets/django_secret
      DATABASE_URL_FILE: /run/secrets/db_url
      CACHE_URL: redis://redis
      EMAIL_HOST_PASSWORD_FILE: /run/secrets/email_password
      EMAIL_HOST_USER_FILE: /run/secrets/email_user
      EMAIL_HOST_FILE: /run/secrets/email_host
      STRIPE_PK_FILE: /run/secrets/stripe_pk
      STRIPE_SK_FILE: /run/secrets/stripe_sk
      GIGO_PASSWORD_FILE: /run/secrets/gigo_password
      GIGO_EMAIL_FILE: /run/secrets/gigo_email
      MAILGUN_KEY_FILE: /run/secrets/mailgun_key
    secrets:
      - django_secret
      - email_password
      - email_user
      - email_host
      - db_url
      - stripe_pk
      - stripe_sk
      - gigo_email
      - gigo_password
      - mailgun_key
    volumes:
      - /srv/streetnoise.at/media:/code/media:rw
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
      - redis:redis
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
