version: '3.1'
secrets:
  db_password:
    file: ./secrets/db_password
  django_secret:
    file: ./secrets/django_secret
  email_password:
    file: ./secrets/email_password
  db_url:
    file: ./secrets/db_url
  stripe_pk:
    file: ./secrets/stripe_pk
  stripe_sk:
    file: ./secrets/stripe_sk
services:
  db:
    environment:
      POSTGRES_DB: streetnoise_cms
      POSTGRES_USER: streetnoise_cms
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    user: "3993:3993"
    restart: always
    image: postgres:9.6
    expose:
      - "5432"
    volumes:
      - /srv/streetnoise.at/postgres:/var/lib/postgresql/data/:rw
      - /etc/passwd:/etc/passwd:ro
    secrets:
      - db_password
  redis:
    restart: always
    image: redis:3.0
    expose:
      - "6379"
  cms:
    environment:
      DJANGO_SECRET_KEY_FILE: /run/secrets/django_secret
      DATABASE_URL_FILE: /run/secrets/db_url
      CACHE_URL: redis://redis
      EMAIL_HOST_PASSWORD_FILE: /run/secrets/email_password
      STRIPE_PK_FILE: /run/secrets/stripe_pk
      STRIPE_SK_FILE: /run/secrets/stripe_sk
    secrets:
      - django_secret
      - email_password
      - db_url
      - stripe_pk
      - stripe_sk
    volumes:
      - /srv/streetnoise.at/media:/code/media:rw
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
      - redis:redis
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
