# Generated by Django 4.0.8 on 2023-05-02 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crowdfunding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="paid_dt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="donation",
            name="payment_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="donation",
            name="payment_link",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaign_name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["payment_id"], name="crowdfundin_payment_b1bc8d_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["paid_dt"], name="crowdfundin_paid_dt_4cfe14_idx"),
        ),
    ]
