# Generated by Django 4.0.8 on 2023-05-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0002_donation_paid_dt_donation_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='payment_link',
            new_name='product_id',
        ),
    ]
