# Generated by Django 4.1.9 on 2023-05-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crowdfunding", "0003_rename_payment_link_donation_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="stretch_goal1",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="stretch_goal2",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
