# Generated by Django 4.0.7 on 2022-09-20 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birdsong', '0007_alter_contacttag_tag'),
        ('newsletter', '0002_alter_newsletter_header_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedContact',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='birdsong.contact')),
                ('name', models.CharField(max_length=255)),
                ('first_optin_at', models.DateTimeField(blank=True, null=True)),
                ('double_optin_at', models.DateTimeField(blank=True, null=True)),
                ('consented_from', models.CharField(max_length=255)),
                ('consent_withdrawn_at', models.CharField(max_length=255)),
                ('subscribed', models.BooleanField(default=False, help_text='If the user should recieve emails or not')),
            ],
            options={
                'abstract': False,
            },
            bases=('birdsong.contact',),
        ),
    ]
