# Generated by Django 4.0.7 on 2022-09-21 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0002_alter_newsletter_header_background"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "contact_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="birdsong.contact",
                    ),
                ),
                ("name", models.CharField(help_text="The user's name", max_length=255)),
                (
                    "first_optin_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the subscriber first asked to receive newsletters",
                        null=True,
                    ),
                ),
                (
                    "double_optin_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the subscriber confirmed their email address",
                        null=True,
                    ),
                ),
                (
                    "consented_from",
                    models.CharField(
                        blank=True,
                        help_text="Where/How the user consented",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "consent_withdrawn_at",
                    models.CharField(
                        blank=True,
                        help_text="When the user unsubscribed",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "subscribed",
                    models.BooleanField(
                        default=False,
                        help_text="If the user should recieve emails or not",
                    ),
                ),
                (
                    "bounce_score",
                    models.IntegerField(default=0, help_text="The subscriber's current bounce score"),
                ),
                (
                    "reset_bounce_score_on",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the bounce score should be reset",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscriber",
                "verbose_name_plural": "Subscribers",
            },
            bases=("birdsong.contact",),
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "verbose_name": "SNOZeitung Issue",
                "verbose_name_plural": "SNOZeitung Issues",
            },
        ),
    ]
