# Generated by Django 4.0.7 on 2022-09-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_extendedcontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendedcontact',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
