# Generated by Django 4.1.13 on 2026-05-19 08:19

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_newslettersubscriber_alter_newsletter_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "rich_text",
                        wagtail.blocks.RichTextBlock(
                            features=["h3", "h4", "bold", "italic", "link", "ul", "ol", "document-link"],
                            template="birdsong/mail/blocks/richtext.html",
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
    ]
