# Generated by Django 4.0.7 on 2022-09-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newslettersubscriber_alter_newsletter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='bounce_score',
            field=models.IntegerField(default=0, help_text="The subscriber's current bounce score"),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='reset_bounce_score_on',
            field=models.DateTimeField(blank=True, help_text='When the bounce score should be reset', null=True),
        ),
    ]
