# Generated by Django 4.0.7 on 2022-09-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_alter_extendedcontact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedcontact',
            name='consent_withdrawn_at',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extendedcontact',
            name='consented_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
