# Generated by Django 4.0.7 on 2022-10-19 14:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalPage2023',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_template', models.CharField(choices=[('festival2023/homepage.html', 'Home Page')], default='festival2023/homepage.html', max_length=255)),
                ('body', wagtail.fields.StreamField([('heading_text', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=255, required=True)), ('text', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'bold', 'italic', 'strikethrough', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'blockquote']))])), ('paragraph_image', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=255, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(group='Image', required=True)), ('image_alignment', wagtail.blocks.ChoiceBlock(choices=[('', 'Select Image alignment'), ('left', 'Image Left'), ('right', 'Image Right')], group='Image')), ('body', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'strikethrough', 'ol', 'ul', 'hr', 'link', 'document-link', 'blockquote'], required=True))])), ('image_grid', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.blocks.TextBlock(required=False)), ('attribution', wagtail.blocks.TextBlock(required=False, verbose_name='Photographer Credit')), ('attribution_url', wagtail.blocks.URLBlock(required=False, vervose_name='Photographer URL'))]), icon='image', template='home/blocks/image_grid.html'))])), ('number_boxes', wagtail.blocks.StructBlock([('boxes', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('value', wagtail.blocks.CharBlock(max_length=40, required=True)), ('label', wagtail.blocks.TextBlock(max_length=200, required=True))])))])), ('lineup', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=255, required=True)), ('performers', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=255, required=True)), ('location', wagtail.blocks.CharBlock(max_length=255, required=True)), ('website', wagtail.blocks.URLBlock(required=False)), ('social', wagtail.blocks.URLBlock(required=False)), ('logo', wagtail.images.blocks.ImageChooserBlock(required=True))])))])), ('funders', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=255, required=True)), ('funders', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=255, required=True)), ('logo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('url', wagtail.blocks.URLBlock(required=False))])))])), ('program', wagtail.blocks.StructBlock([]))], blank=True, null=True, use_json_field=None)),
                ('feed_image', models.ForeignKey(blank=True, help_text='The image shown on Facebook and other social media', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
