# Generated by Django 4.0.8 on 2023-05-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("festival2023", "0009_festivalpage2023_crowdfunding_campign"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="festivalpage2023",
            name="crowdfunding_campign",
        ),
        migrations.AddField(
            model_name="festivalpage2023",
            name="crowdfunding_campaign",
            field=models.CharField(
                blank=True, choices=[("test", "test")], default="festival2023/homepage.html", max_length=255
            ),
        ),
    ]
