# Generated by Django 3.0.6 on 2020-06-04 13:23

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('blog', '0003_auto_20200105_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='description_de',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='description_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_de',
            field=models.CharField(max_length=80, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_en',
            field=models.CharField(max_length=80, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='feed_image',
            field=models.ForeignKey(blank=True, help_text='The image shown on Facebook and other social media', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body_de',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(classname='full title', icon='media')), ('image_carousel', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.TextBlock(required=False)), ('video', wagtail.embeds.blocks.EmbedBlock(required=False))]), icon='image', template='blog/blocks/carousel.html'))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body_en',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(classname='full title', icon='media')), ('image_carousel', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.TextBlock(required=False)), ('video', wagtail.embeds.blocks.EmbedBlock(required=False))]), icon='image', template='blog/blocks/carousel.html'))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='feed_image',
            field=models.ForeignKey(blank=True, help_text='The image shown on Facebook and other social media', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(classname='full title', icon='media')), ('image_carousel', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.TextBlock(required=False)), ('video', wagtail.embeds.blocks.EmbedBlock(required=False))]), icon='image', template='blog/blocks/carousel.html'))], blank=True, null=True),
        ),
    ]
