# Generated by Django 4.0.8 on 2023-03-31 11:01

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_blogcategory_id_alter_blogcategoryblogpage_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title")),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "h1",
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "bold",
                                "italic",
                                "strikethrough",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                            ]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock(icon="image")),
                    (
                        "embedded_video",
                        wagtail.embeds.blocks.EmbedBlock(
                            help_text="Paste a link to a video, audio file, instagram, etc.",
                            icon="media",
                            label="Embed media",
                        ),
                    ),
                    (
                        "image_carousel",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                                    ("caption", wagtail.blocks.TextBlock(required=False)),
                                    ("video", wagtail.embeds.blocks.EmbedBlock(required=False)),
                                ]
                            ),
                            icon="image",
                            template="blog/blocks/carousel.html",
                        ),
                    ),
                    (
                        "button",
                        wagtail.blocks.StructBlock(
                            [
                                ("button_text", wagtail.blocks.CharBlock(blank=True)),
                                ("button_url", wagtail.blocks.URLBlock(label="Button link")),
                            ]
                        ),
                    ),
                    (
                        "newsletter_signup",
                        wagtail.blocks.StructBlock(
                            [
                                ("cta_title", wagtail.blocks.CharBlock(blank=True, verbose_name="Title")),
                                ("cta_subtitle", wagtail.blocks.CharBlock(blank=True, verbose_name="Subtitle")),
                                (
                                    "newsletter_type",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Select Type of Newsletter"),
                                            ("generic-newsletter", "Generic"),
                                            ("festival-newsletter", "Festival (Green)"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image_grid",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "images",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("image", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                                ("caption", wagtail.blocks.TextBlock(required=False)),
                                                (
                                                    "attribution",
                                                    wagtail.blocks.TextBlock(
                                                        required=False, verbose_name="Photographer Credit"
                                                    ),
                                                ),
                                                (
                                                    "attribution_url",
                                                    wagtail.blocks.URLBlock(
                                                        required=False, vervose_name="Photographer URL"
                                                    ),
                                                ),
                                            ]
                                        ),
                                        icon="image",
                                        template="home/blocks/image_grid.html",
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "imagetile",
                        wagtail.blocks.StreamBlock(
                            [("image", wagtail.images.blocks.ImageChooserBlock())], label="Image Tile (old)"
                        ),
                    ),
                    (
                        "imagetile2",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "aspect_ratio",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Select Aspect Ratio of Images"),
                                            ("1:1", "1:1 Square"),
                                            ("1:1 sm", "1:1 Square (smaller)"),
                                            ("3:2", "3:2"),
                                            ("4:3", "4:3 (traditional)"),
                                            ("16:9", "16:9 (widescreen)"),
                                        ]
                                    ),
                                ),
                                (
                                    "images",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("image", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                                ("caption", wagtail.blocks.TextBlock(required=False)),
                                                (
                                                    "attribution",
                                                    wagtail.blocks.TextBlock(
                                                        required=False, verbose_name="Photographer Credit"
                                                    ),
                                                ),
                                                (
                                                    "attribution_url",
                                                    wagtail.blocks.URLBlock(
                                                        required=False, vervose_name="Photographer URL"
                                                    ),
                                                ),
                                            ]
                                        ),
                                        icon="image",
                                    ),
                                ),
                            ],
                            label="Image Tile (new!)",
                        ),
                    ),
                    (
                        "paragraph_image",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.CharBlock(max_length=255, required=True)),
                                ("image", wagtail.images.blocks.ImageChooserBlock(group="Image", required=True)),
                                (
                                    "image_alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Select Image alignment"),
                                            ("left", "Image Left"),
                                            ("right", "Image Right"),
                                        ],
                                        group="Image",
                                    ),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "strikethrough",
                                            "ol",
                                            "ul",
                                            "hr",
                                            "link",
                                            "document-link",
                                            "blockquote",
                                        ],
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=None,
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body_de",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title")),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "h1",
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "bold",
                                "italic",
                                "strikethrough",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                            ]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock(icon="image")),
                    (
                        "embedded_video",
                        wagtail.embeds.blocks.EmbedBlock(
                            help_text="Paste a link to a video, audio file, instagram, etc.",
                            icon="media",
                            label="Embed media",
                        ),
                    ),
                    (
                        "image_carousel",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                                    ("caption", wagtail.blocks.TextBlock(required=False)),
                                    ("video", wagtail.embeds.blocks.EmbedBlock(required=False)),
                                ]
                            ),
                            icon="image",
                            template="blog/blocks/carousel.html",
                        ),
                    ),
                    (
                        "button",
                        wagtail.blocks.StructBlock(
                            [
                                ("button_text", wagtail.blocks.CharBlock(blank=True)),
                                ("button_url", wagtail.blocks.URLBlock(label="Button link")),
                            ]
                        ),
                    ),
                    (
                        "newsletter_signup",
                        wagtail.blocks.StructBlock(
                            [
                                ("cta_title", wagtail.blocks.CharBlock(blank=True, verbose_name="Title")),
                                ("cta_subtitle", wagtail.blocks.CharBlock(blank=True, verbose_name="Subtitle")),
                                (
                                    "newsletter_type",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Select Type of Newsletter"),
                                            ("generic-newsletter", "Generic"),
                                            ("festival-newsletter", "Festival (Green)"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image_grid",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "images",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("image", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                                ("caption", wagtail.blocks.TextBlock(required=False)),
                                                (
                                                    "attribution",
                                                    wagtail.blocks.TextBlock(
                                                        required=False, verbose_name="Photographer Credit"
                                                    ),
                                                ),
                                                (
                                                    "attribution_url",
                                                    wagtail.blocks.URLBlock(
                                                        required=False, vervose_name="Photographer URL"
                                                    ),
                                                ),
                                            ]
                                        ),
                                        icon="image",
                                        template="home/blocks/image_grid.html",
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "imagetile",
                        wagtail.blocks.StreamBlock(
                            [("image", wagtail.images.blocks.ImageChooserBlock())], label="Image Tile (old)"
                        ),
                    ),
                    (
                        "imagetile2",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "aspect_ratio",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Select Aspect Ratio of Images"),
                                            ("1:1", "1:1 Square"),
                                            ("1:1 sm", "1:1 Square (smaller)"),
                                            ("3:2", "3:2"),
                                            ("4:3", "4:3 (traditional)"),
                                            ("16:9", "16:9 (widescreen)"),
                                        ]
                                    ),
                                ),
                                (
                                    "images",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("image", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                                ("caption", wagtail.blocks.TextBlock(required=False)),
                                                (
                                                    "attribution",
                                                    wagtail.blocks.TextBlock(
                                                        required=False, verbose_name="Photographer Credit"
                                                    ),
                                                ),
                                                (
                                                    "attribution_url",
                                                    wagtail.blocks.URLBlock(
                                                        required=False, vervose_name="Photographer URL"
                                                    ),
                                                ),
                                            ]
                                        ),
                                        icon="image",
                                    ),
                                ),
                            ],
                            label="Image Tile (new!)",
                        ),
                    ),
                    (
                        "paragraph_image",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.CharBlock(max_length=255, required=True)),
                                ("image", wagtail.images.blocks.ImageChooserBlock(group="Image", required=True)),
                                (
                                    "image_alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Select Image alignment"),
                                            ("left", "Image Left"),
                                            ("right", "Image Right"),
                                        ],
                                        group="Image",
                                    ),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "strikethrough",
                                            "ol",
                                            "ul",
                                            "hr",
                                            "link",
                                            "document-link",
                                            "blockquote",
                                        ],
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=None,
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body_en",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title")),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "h1",
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "bold",
                                "italic",
                                "strikethrough",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                            ]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock(icon="image")),
                    (
                        "embedded_video",
                        wagtail.embeds.blocks.EmbedBlock(
                            help_text="Paste a link to a video, audio file, instagram, etc.",
                            icon="media",
                            label="Embed media",
                        ),
                    ),
                    (
                        "image_carousel",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                                    ("caption", wagtail.blocks.TextBlock(required=False)),
                                    ("video", wagtail.embeds.blocks.EmbedBlock(required=False)),
                                ]
                            ),
                            icon="image",
                            template="blog/blocks/carousel.html",
                        ),
                    ),
                    (
                        "button",
                        wagtail.blocks.StructBlock(
                            [
                                ("button_text", wagtail.blocks.CharBlock(blank=True)),
                                ("button_url", wagtail.blocks.URLBlock(label="Button link")),
                            ]
                        ),
                    ),
                    (
                        "newsletter_signup",
                        wagtail.blocks.StructBlock(
                            [
                                ("cta_title", wagtail.blocks.CharBlock(blank=True, verbose_name="Title")),
                                ("cta_subtitle", wagtail.blocks.CharBlock(blank=True, verbose_name="Subtitle")),
                                (
                                    "newsletter_type",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Select Type of Newsletter"),
                                            ("generic-newsletter", "Generic"),
                                            ("festival-newsletter", "Festival (Green)"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image_grid",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "images",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("image", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                                ("caption", wagtail.blocks.TextBlock(required=False)),
                                                (
                                                    "attribution",
                                                    wagtail.blocks.TextBlock(
                                                        required=False, verbose_name="Photographer Credit"
                                                    ),
                                                ),
                                                (
                                                    "attribution_url",
                                                    wagtail.blocks.URLBlock(
                                                        required=False, vervose_name="Photographer URL"
                                                    ),
                                                ),
                                            ]
                                        ),
                                        icon="image",
                                        template="home/blocks/image_grid.html",
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "imagetile",
                        wagtail.blocks.StreamBlock(
                            [("image", wagtail.images.blocks.ImageChooserBlock())], label="Image Tile (old)"
                        ),
                    ),
                    (
                        "imagetile2",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "aspect_ratio",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Select Aspect Ratio of Images"),
                                            ("1:1", "1:1 Square"),
                                            ("1:1 sm", "1:1 Square (smaller)"),
                                            ("3:2", "3:2"),
                                            ("4:3", "4:3 (traditional)"),
                                            ("16:9", "16:9 (widescreen)"),
                                        ]
                                    ),
                                ),
                                (
                                    "images",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("image", wagtail.images.blocks.ImageChooserBlock(required=True)),
                                                ("caption", wagtail.blocks.TextBlock(required=False)),
                                                (
                                                    "attribution",
                                                    wagtail.blocks.TextBlock(
                                                        required=False, verbose_name="Photographer Credit"
                                                    ),
                                                ),
                                                (
                                                    "attribution_url",
                                                    wagtail.blocks.URLBlock(
                                                        required=False, vervose_name="Photographer URL"
                                                    ),
                                                ),
                                            ]
                                        ),
                                        icon="image",
                                    ),
                                ),
                            ],
                            label="Image Tile (new!)",
                        ),
                    ),
                    (
                        "paragraph_image",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.CharBlock(max_length=255, required=True)),
                                ("image", wagtail.images.blocks.ImageChooserBlock(group="Image", required=True)),
                                (
                                    "image_alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Select Image alignment"),
                                            ("left", "Image Left"),
                                            ("right", "Image Right"),
                                        ],
                                        group="Image",
                                    ),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "strikethrough",
                                            "ol",
                                            "ul",
                                            "hr",
                                            "link",
                                            "document-link",
                                            "blockquote",
                                        ],
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=None,
            ),
        ),
    ]
