# Generated by Django 4.1.9 on 2023-06-30 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("blog", "0015_alter_blogpage_body_alter_blogpage_body_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="thumbnail_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Should be 4:3 aspect ratio, at least 1000x750 pixels",
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="header_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Should be at least 1908x700 pixels.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Header image",
            ),
        ),
    ]
