# Generated by Django 4.1.13 on 2023-11-19 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("blog", "0016_blogpage_thumbnail_image_alter_blogpage_header_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="thumbnail_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Should be 4:3 aspect ratio, at least 1000x750 pixels",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
