# Generated by Django 4.0.7 on 2022-09-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailmenus", "0024_auto_20200608_1049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flatmenu",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="flatmenuitem",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="mainmenu",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="mainmenuitem",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
