# Generated by Django 4.1.13 on 2023-11-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="songpage",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("retired", "Retired")], default="active", max_length=255
            ),
        ),
    ]
