# Generated by Django 4.1.13 on 2023-11-20 15:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0002_songpage_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="songpage",
            name="lyrics",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Lyrics"),
        ),
        migrations.AlterField(
            model_name="songpage",
            name="arrangement_notes",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Our notes for the arrangement", verbose_name="Arrangement Notes"
            ),
        ),
    ]
