# Generated by Django 4.1.13 on 2023-11-20 15:33

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0003_songpage_lyrics_alter_songpage_arrangement_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="songpage",
            name="last_played_date",
            field=models.DateField(blank=True, null=True, verbose_name="Last Played"),
        ),
        migrations.AlterField(
            model_name="songpage",
            name="lyrics",
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name="Lyrics"),
        ),
    ]
