# Generated by Django 4.1.13 on 2023-11-20 16:50

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0004_songpage_last_played_date_alter_songpage_lyrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songpage",
            name="arrangement_notes",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Our notes for the arrangement", null=True, verbose_name="Arrangement Notes"
            ),
        ),
    ]
