# Generated by Django 4.1.13 on 2023-11-21 08:31

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0005_alter_songpage_arrangement_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songpage",
            name="arrangement_notes",
            field=wagtailmarkdown.fields.MarkdownField(
                blank=True, help_text="Our notes for the arrangement", null=True, verbose_name="Arrangement Notes"
            ),
        ),
        migrations.AlterField(
            model_name="songpage",
            name="description",
            field=wagtailmarkdown.fields.MarkdownField(
                blank=True, help_text="A sentence or two describing the song.", verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="songpage",
            name="description_de",
            field=wagtailmarkdown.fields.MarkdownField(
                blank=True, help_text="A sentence or two describing the song.", null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="songpage",
            name="description_en",
            field=wagtailmarkdown.fields.MarkdownField(
                blank=True, help_text="A sentence or two describing the song.", null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="songpage",
            name="lyrics",
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, verbose_name="Lyrics"),
        ),
    ]
