# Generated by Django 4.1.13 on 2023-11-21 15:35

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0006_alter_songpage_arrangement_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="songindexpage",
            name="intro_de",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="songindexpage",
            name="intro_en",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
