# Generated by Django 2.2.1 on 2019-05-06 15:46

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("home", "0002_auto_20190506_1522"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPrivacyPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "privacy_content",
                    wagtail.fields.StreamField(
                        [("heading", wagtail.blocks.CharBlock()), ("paragraph", wagtail.blocks.RichTextBlock())],
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "privacy_content_de",
                    wagtail.fields.StreamField(
                        [("heading", wagtail.blocks.CharBlock()), ("paragraph", wagtail.blocks.RichTextBlock())],
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "privacy_content_en",
                    wagtail.fields.StreamField(
                        [("heading", wagtail.blocks.CharBlock()), ("paragraph", wagtail.blocks.RichTextBlock())],
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ImpressumPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "impressum_content",
                    wagtail.fields.StreamField(
                        [("heading", wagtail.blocks.CharBlock()), ("paragraph", wagtail.blocks.RichTextBlock())],
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "impressum_content_de",
                    wagtail.fields.StreamField(
                        [("heading", wagtail.blocks.CharBlock()), ("paragraph", wagtail.blocks.RichTextBlock())],
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "impressum_content_en",
                    wagtail.fields.StreamField(
                        [("heading", wagtail.blocks.CharBlock()), ("paragraph", wagtail.blocks.RichTextBlock())],
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
