# Generated by Django 2.2.1 on 2019-05-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dataprivacypage_impressumpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandfriend',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='bandfriend',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
