# Generated by Django 2.2.1 on 2019-05-08 11:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0006_auto_20190507_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('donation_intro', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.RichTextBlock())], blank=True, null=True)),
                ('donation_intro_de', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.RichTextBlock())], blank=True, null=True)),
                ('donation_intro_en', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.RichTextBlock())], blank=True, null=True)),
                ('label_donation_amount', models.CharField(blank=True, max_length=100)),
                ('label_donation_amount_de', models.CharField(blank=True, max_length=100, null=True)),
                ('label_donation_amount_en', models.CharField(blank=True, max_length=100, null=True)),
                ('label_donation', models.CharField(blank=True, help_text='The word "donation" used on the official donation receipt', max_length=100, verbose_name='Donation line item')),
                ('label_donation_de', models.CharField(blank=True, help_text='The word "donation" used on the official donation receipt', max_length=100, null=True, verbose_name='Donation line item')),
                ('label_donation_en', models.CharField(blank=True, help_text='The word "donation" used on the official donation receipt', max_length=100, null=True, verbose_name='Donation line item')),
                ('label_donation_detail', models.CharField(blank=True, help_text='A small description of the donation used on the official donation receipt', max_length=255, verbose_name='Donation line item description')),
                ('label_donation_detail_de', models.CharField(blank=True, help_text='A small description of the donation used on the official donation receipt', max_length=255, null=True, verbose_name='Donation line item description')),
                ('label_donation_detail_en', models.CharField(blank=True, help_text='A small description of the donation used on the official donation receipt', max_length=255, null=True, verbose_name='Donation line item description')),
                ('thank_you', models.CharField(blank=True, help_text='The title displayed after the user successful donates.', max_length=100)),
                ('thank_you_de', models.CharField(blank=True, help_text='The title displayed after the user successful donates.', max_length=100, null=True)),
                ('thank_you_en', models.CharField(blank=True, help_text='The title displayed after the user successful donates.', max_length=100, null=True)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, help_text='Text displayed after the user successful donates.')),
                ('thank_you_text_de', wagtail.fields.RichTextField(blank=True, help_text='Text displayed after the user successful donates.', null=True)),
                ('thank_you_text_en', wagtail.fields.RichTextField(blank=True, help_text='Text displayed after the user successful donates.', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
