# Generated by Django 2.2.3 on 2019-07-26 13:57

import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("home", "0007_donationpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("heading", wagtail.blocks.CharBlock()),
                            ("paragraph", wagtail.blocks.RichTextBlock()),
                            ("image", wagtail.images.blocks.ImageChooserBlock()),
                            ("rawhtml", wagtail.blocks.RawHTMLBlock()),
                            ("quote", wagtail.blocks.BlockQuoteBlock()),
                            ("embed", wagtail.embeds.blocks.EmbedBlock()),
                        ],
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "content_de",
                    wagtail.fields.StreamField(
                        [
                            ("heading", wagtail.blocks.CharBlock()),
                            ("paragraph", wagtail.blocks.RichTextBlock()),
                            ("image", wagtail.images.blocks.ImageChooserBlock()),
                            ("rawhtml", wagtail.blocks.RawHTMLBlock()),
                            ("quote", wagtail.blocks.BlockQuoteBlock()),
                            ("embed", wagtail.embeds.blocks.EmbedBlock()),
                        ],
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "content_en",
                    wagtail.fields.StreamField(
                        [
                            ("heading", wagtail.blocks.CharBlock()),
                            ("paragraph", wagtail.blocks.RichTextBlock()),
                            ("image", wagtail.images.blocks.ImageChooserBlock()),
                            ("rawhtml", wagtail.blocks.RawHTMLBlock()),
                            ("quote", wagtail.blocks.BlockQuoteBlock()),
                            ("embed", wagtail.embeds.blocks.EmbedBlock()),
                        ],
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
