# Generated by Django 2.2.3 on 2019-07-26 17:07

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_auto_20190726_1450"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock()),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("rawhtml", wagtail.blocks.RawHTMLBlock()),
                    ("quote", wagtail.blocks.BlockQuoteBlock()),
                    ("embed", wagtail.embeds.blocks.EmbedBlock()),
                    ("imagetile", wagtail.blocks.StreamBlock([("image", wagtail.images.blocks.ImageChooserBlock())])),
                    (
                        "footercta",
                        wagtail.blocks.StructBlock(
                            [
                                ("cta_title", wagtail.blocks.CharBlock(blank=True, verbose_name="CTA Title")),
                                ("cta_subtitle", wagtail.blocks.CharBlock(blank=True, verbose_name="CTA Subtitle")),
                                ("cta_button1", wagtail.blocks.CharBlock(blank=True, verbose_name="Button 1 Text")),
                                ("cta_button2", wagtail.blocks.CharBlock(blank=True, verbose_name="Button 2 Text")),
                                ("cta_button1_url", wagtail.blocks.URLBlock(classname="full title")),
                                ("cta_button2_url", wagtail.blocks.URLBlock(classname="full title")),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="genericpage",
            name="content_de",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock()),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("rawhtml", wagtail.blocks.RawHTMLBlock()),
                    ("quote", wagtail.blocks.BlockQuoteBlock()),
                    ("embed", wagtail.embeds.blocks.EmbedBlock()),
                    ("imagetile", wagtail.blocks.StreamBlock([("image", wagtail.images.blocks.ImageChooserBlock())])),
                    (
                        "footercta",
                        wagtail.blocks.StructBlock(
                            [
                                ("cta_title", wagtail.blocks.CharBlock(blank=True, verbose_name="CTA Title")),
                                ("cta_subtitle", wagtail.blocks.CharBlock(blank=True, verbose_name="CTA Subtitle")),
                                ("cta_button1", wagtail.blocks.CharBlock(blank=True, verbose_name="Button 1 Text")),
                                ("cta_button2", wagtail.blocks.CharBlock(blank=True, verbose_name="Button 2 Text")),
                                ("cta_button1_url", wagtail.blocks.URLBlock(classname="full title")),
                                ("cta_button2_url", wagtail.blocks.URLBlock(classname="full title")),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="genericpage",
            name="content_en",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock()),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("rawhtml", wagtail.blocks.RawHTMLBlock()),
                    ("quote", wagtail.blocks.BlockQuoteBlock()),
                    ("embed", wagtail.embeds.blocks.EmbedBlock()),
                    ("imagetile", wagtail.blocks.StreamBlock([("image", wagtail.images.blocks.ImageChooserBlock())])),
                    (
                        "footercta",
                        wagtail.blocks.StructBlock(
                            [
                                ("cta_title", wagtail.blocks.CharBlock(blank=True, verbose_name="CTA Title")),
                                ("cta_subtitle", wagtail.blocks.CharBlock(blank=True, verbose_name="CTA Subtitle")),
                                ("cta_button1", wagtail.blocks.CharBlock(blank=True, verbose_name="Button 1 Text")),
                                ("cta_button2", wagtail.blocks.CharBlock(blank=True, verbose_name="Button 2 Text")),
                                ("cta_button1_url", wagtail.blocks.URLBlock(classname="full title")),
                                ("cta_button2_url", wagtail.blocks.URLBlock(classname="full title")),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
