# Generated by Django 2.2.3 on 2019-07-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190726_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='cta_button1',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTA Button 1 Text'),
        ),
        migrations.AddField(
            model_name='genericpage',
            name='cta_button1_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='genericpage',
            name='cta_button2',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTA Button 2 Text'),
        ),
        migrations.AddField(
            model_name='genericpage',
            name='cta_button2_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='genericpage',
            name='cta_subtitle',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTA Subtitle'),
        ),
        migrations.AddField(
            model_name='genericpage',
            name='cta_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTA Title'),
        ),
    ]
