# Generated by Django 3.0.7 on 2020-06-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0014_homepage2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impressumpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='DataPrivacyPage',
        ),
        migrations.DeleteModel(
            name='ImpressumPage',
        ),
    ]
