# Generated by Django 3.0.7 on 2020-06-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0015_auto_20200605_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpage',
            name='feed_image',
            field=models.ForeignKey(blank=True, help_text='The image shown on Facebook and other social media', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='genericpage',
            name='feed_image',
            field=models.ForeignKey(blank=True, help_text='The image shown on Facebook and other social media', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='gigrequestpage',
            name='feed_image',
            field=models.ForeignKey(blank=True, help_text='The image shown on Facebook and other social media', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
