# Generated by Django 4.0.7 on 2022-09-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_auto_20200610_0635"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bandfriend",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="gigrequest",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="gigtype",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
