# Generated by Django 2.2.1 on 2019-05-07 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gigs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gigpage",
            name="feed_image",
            field=models.ForeignKey(
                blank=True,
                help_text="The gig banner image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
    ]
