# Generated by Django 3.0.7 on 2020-06-05 11:05

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0022_uploadedimage"),
        ("gigs", "0002_auto_20190507_1257"),
    ]

    operations = [
        migrations.AddField(
            model_name="gigpage",
            name="body_de",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="A sentence or two describing the gig.", null=True, verbose_name="Details"
            ),
        ),
        migrations.AddField(
            model_name="gigpage",
            name="body_en",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="A sentence or two describing the gig.", null=True, verbose_name="Details"
            ),
        ),
        migrations.AlterField(
            model_name="gigpage",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="A sentence or two describing the gig.", verbose_name="Details"
            ),
        ),
        migrations.AlterField(
            model_name="gigpage",
            name="call_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Call time"),
        ),
        migrations.AlterField(
            model_name="gigpage",
            name="feed_image",
            field=models.ForeignKey(
                blank=True,
                help_text="An image representing the gig or organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
                verbose_name="Gig Image",
            ),
        ),
        migrations.AlterField(
            model_name="gigpage",
            name="gigomatic_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="gigpage",
            name="partner",
            field=models.CharField(
                blank=True, help_text="The organization we're doing the gig with", max_length=255, null=True
            ),
        ),
    ]
