# Generated by Django 3.0.7 on 2020-06-05 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('gigs', '0004_auto_20200605_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigpage',
            name='feed_image',
            field=models.ForeignKey(blank=True, help_text='A photo representing the gig or organization. Best if it has a 2x1 aspect ratio (example: 800x400).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Gig Image'),
        ),
    ]
