# Generated by Django 4.0.7 on 2022-09-21 12:52

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gigs", "0005_auto_20200605_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="gigpage",
            name="body2",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title")),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "h1",
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "bold",
                                "italic",
                                "strikethrough",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "blockquote",
                            ]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock(icon="image")),
                    (
                        "embedded_video",
                        wagtail.embeds.blocks.EmbedBlock(
                            help_text="Paste a link to a video, audio file, instagram, etc.",
                            icon="media",
                            label="Embed media",
                        ),
                    ),
                    (
                        "button",
                        wagtail.blocks.StructBlock(
                            [
                                ("button_text", wagtail.blocks.CharBlock(blank=True)),
                                ("button_url", wagtail.blocks.URLBlock(label="Button link")),
                            ]
                        ),
                    ),
                ],
                blank=True,
                help_text="A sentence or two describing the gig.",
                null=True,
                use_json_field=None,
            ),
        ),
    ]
