---
name: Deploy Service

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]  # Replace with the actual name of your build and publish workflow
    branches: [main]
    types:
      - completed


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          chmod 0700 ~/.ssh
          mkdir -p ~/.ssh
          touch ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          touch ~/.ssh/known_hosts
          chmod 640 ~/.ssh/known_hosts
          ssh-keyscan -t ssh-ed25519 ${{ secrets.SERVER_SSH }} >> ~/.ssh/known_hosts

      - name: Deploy the service
        run: ssh ${{ secrets.SERVER_SSH }} '/usr/local/bin/deploy-service streetnoise.at'
